name: CI
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install matplotlib || true
      - name: Generate artifacts
        run: |
          . .venv/bin/activate
          python scripts/generate_artifacts.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            artifacts/b_field_centerline.png
            artifacts/b_field_plane.png
            artifacts/field_kpis.json
            feasibility_gates_report.json
